arcoiris=("Azul","Verde","Rojo","Amarillo")
print(arcoiris)
print("--longitud arcoiris--")
print(len(arcoiris))
Animales=("pantera",20,"estatura",1.7)
print(Animales)
print("Elementos de la tupla")
print(Animales[2])
rateros = ("Juan", "Ana", "Pedro")
y = list(rateros)
y[0] = "Polainas"
x = tuple(y)
print(x)
print("--Agregar elemento--")
Nanimal=("Boby","Chetos")
y = list(Nanimal)
print(y)
y.append("Tontolin")
Otratupla = tuple(y)
print(Otratupla)
print("Uso de for en tuplas")
for elcolor in arcoiris:
    print(elcolor)